---
title: "Kuruka"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(svglite))
library(Biostrings)
theme_set(theme_bw())
```

SRR13070742_1.fastq.gz --> D. bocqueti
SRR13070599_1.fastq.gz --> D. erecta

```{}
seqtk seq -A SRR13070742_1.fastq.gz > SRR13070742_1.fasta

for i in *.fasta; do /home/riccardo/repeatannotation/RepeatMasker/RepeatMasker -pa 60 -no_is -s -nolow -dir RM-out/ -lib ../ref/kuruka.fasta $i;done
```

```{r}
columns_RM <- c("SWscore", "pdiv", "pdel", "pins", "contig", "qstart", "qend", "qleft",  "strand", "te", "class", "position_in_repeat_begin", "position_in_repeat_end", "position_in_repeat_left", "ID")

raw_erecta <- read_table("/Volumes/Storage/kuruka/derecta/raw-reads/RM-out/SRR13070599_1.fasta.defrag.out", col_names = columns_RM) %>% arrange(desc(SWscore)) %>% mutate(species = "D.erecta")

raw_bocqueti <- read_table("/Volumes/Storage/kuruka/derecta/raw-reads/RM-out/SRR13070742_1.fasta.defrag.out", col_names = columns_RM) %>% arrange(desc(SWscore)) %>% mutate(species = "D.bocqueti")

(combined_data <- bind_rows(raw_erecta, raw_bocqueti))
```

```{r}
(plottable <- combined_data %>%
  mutate(match_len = qend - qstart) %>%
  group_by(te) %>%
  filter(match_len < 9000) %>%
  arrange(desc(match_len)) %>%
  ungroup())

# Create a data frame for the custom label
label_data <- data.frame(x = 8650, y = 55, label = "Length of Kuruka consensus", realm1 = NA)

# Plot
ggplot(plottable, aes(x = match_len, y = 100 - pdiv)) + 
  geom_point(shape = 21, size = 3, alpha = 0.5, color = "black", aes(fill = species)) +  # Shape 21 = dots with border
  scale_fill_manual(values = c("maroon", "grey")) + 
  geom_vline(xintercept = 8833, linetype = "longdash") +  # Vertical line at 8833
  geom_text(data = label_data, aes(x = x, y = y, label = label), angle = 90, hjust = 0, size = 3.5) +  # Custom label
  labs(x = "Alignment length (bp)", y = "Sequence identity (%)", fill = "Species") + 
  #geom_text_repel(data = plottable %>% filter(match_len > 6500 | (pdiv < 5 & match_len > 1000)), 
  #                aes(label = species), size = 2.8, box.padding = 0.4, max.overlaps = 18) + 
  scale_x_continuous(breaks = c(seq(0, 8000, by = 1000), 8833))  # Set custom x-axis breaks
```
